# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-10 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='udpate',
            new_name='updated',
        ),
    ]
